# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gS-VoPJwK7D5z_p9bNJQaFg0wGUc8_rL
"""

import tensorflow as tf
from tensorflow.keras import layers,models

def create_mlp(input_size, hidden_sizes, output_size):
  model = models.Sequential()
  model.add(layers.InputLayer(input_shape=(input_size,)))
  for hidden_size in hidden_sizes:
    model.add(layers.Dense(hidden_size, activation='relu'))
  model.add(layers.Dense(output_size, activation='softmax'))
  return model


input_size=10
hidden_sizes =[64,32]
output_size= 2
mlp = create_mlp(input_size, hidden_sizes, output_size)
mlp.summary()



