# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gS-VoPJwK7D5z_p9bNJQaFg0wGUc8_rL
"""

import tensorflow as tf
import numpy as np
from tensorflow.keras import models, layers
#define xor input and output
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype = np.float32)
y = np.array([[0], [1], [1], [0]], dtype = np.float32)
#define neural network architecture
model = models.Sequential([
    layers.Dense(2, input_dim = 2, activation = 'sigmoid'),
    layers.Dense(1, activation = 'sigmoid')
])
#compile the model
model.compile(optimizer = 'adam', loss='mean_squared_error', metrics=['accuracy'])

#train the model
model.fit(X, y)

#evaluate the model
prediction = model.predict(X)

print('Input: ', X)
print('Prediction: ', prediction)